import SwiftUI

@available(macOS 26.0, *)
struct ShotProductionStripView: View {
    @Bindable var store: AnimateStore
    let scene: AnimationScene
    let shot: AnimationSceneShot
    let shotIndex: Int

    @State private var firstFramePrompt = ""
    @State private var lastFramePrompt = ""
    @State private var motionDirection = ""
    @State private var durationSeconds: Double = 4.0
    @State private var selectedAspectRatio = "16:9"
    @State private var hasAppeared = false

    private let aspectRatios = ["16:9", "21:9", "4:3"]

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                // Header
                headerSection
                Divider()
                // First/Last frame cards side by side
                framesSection
                Divider()
                // Motion direction
                motionSection
                Divider()
                // Timing and Vidu controls
                viduSection
            }
            .padding()
        }
        .onAppear { loadFromShot() }
    }

    private var headerSection: some View {
        HStack(spacing: 12) {
            VStack(alignment: .leading, spacing: 2) {
                Text("Shot \(shotIndex + 1)")
                    .font(.headline)
                Text(scene.name)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            if let cameraShot = shot.cameraShot {
                Text(cameraShot.rawValue)
                    .font(.caption)
                    .padding(.horizontal, 8).padding(.vertical, 4)
                    .background(.quaternary.opacity(0.2), in: Capsule())
            }
            Text("Duration: \(String(format: "%.1fs", durationSeconds))")
                .font(.caption.monospacedDigit())
                .foregroundStyle(.secondary)
        }
    }

    private var framesSection: some View {
        HStack(alignment: .top, spacing: 12) {
            ShotFrameCard(
                title: "First Frame",
                imagePath: shot.shotFrameGeneration?.firstFrameImagePath,
                prompt: firstFramePrompt,
                variants: shot.shotFrameGeneration?.firstFrameVariants ?? [],
                isApproved: shot.shotFrameGeneration?.firstFrameApproved ?? false,
                onGenerate: { generateFirstFrame() },
                onQueueToggle: { },
                promptText: $firstFramePrompt
            )

            ShotFrameCard(
                title: "Last Frame",
                imagePath: shot.shotFrameGeneration?.lastFrameImagePath,
                prompt: lastFramePrompt,
                variants: shot.shotFrameGeneration?.lastFrameVariants ?? [],
                isApproved: shot.shotFrameGeneration?.lastFrameApproved ?? false,
                onGenerate: { generateLastFrame() },
                onQueueToggle: { },
                promptText: $lastFramePrompt
            )
        }
    }

    private var motionSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Motion Direction")
                    .font(.subheadline.weight(.semibold))
                Spacer()
                Button {
                    autoGenerateDirection()
                } label: {
                    Label("Auto-Generate", systemImage: "sparkles")
                }
                .buttonStyle(.bordered).controlSize(.small)
                .disabled(store.miniMaxAPIKey.isEmpty)
            }

            TextEditor(text: $motionDirection)
                .font(.callout)
                .frame(minHeight: 60, maxHeight: 100)
                .padding(6)
                .background(.quaternary.opacity(0.15), in: RoundedRectangle(cornerRadius: 8))
        }
    }

    private var viduSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("Vidu Q3").font(.subheadline.weight(.semibold))

            HStack(spacing: 16) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Duration").font(.caption)
                    Slider(value: $durationSeconds, in: 0.5...16, step: 0.5)
                        .frame(width: 200)
                    Text("\(String(format: "%.1f", durationSeconds))s (max 16s)")
                        .font(.caption2).foregroundStyle(.secondary)
                }

                VStack(alignment: .leading, spacing: 4) {
                    Text("Aspect Ratio").font(.caption)
                    Picker("", selection: $selectedAspectRatio) {
                        ForEach(aspectRatios, id: \.self) { Text($0) }
                    }
                    .pickerStyle(.segmented)
                    .frame(width: 180)
                }
            }

            HStack(spacing: 8) {
                Button {
                    sendToVidu()
                } label: {
                    Label("Send to Vidu", systemImage: "play.fill")
                }
                .buttonStyle(.borderedProminent).controlSize(.small)
                .disabled(store.viduAPIKey.isEmpty)

                Button {
                    queueForBatch()
                } label: {
                    Label("Queue for Batch", systemImage: "tray.and.arrow.down")
                }
                .buttonStyle(.bordered).controlSize(.small)
            }
        }
    }

    // MARK: - Actions

    private func loadFromShot() {
        let fg = shot.shotFrameGeneration
        firstFramePrompt = fg?.firstFramePrompt ?? ""
        lastFramePrompt = fg?.lastFramePrompt ?? ""
        motionDirection = fg?.motionDirection ?? ""
        durationSeconds = fg?.durationSeconds ?? 4.0
        selectedAspectRatio = fg?.aspectRatio ?? "16:9"
        hasAppeared = true
    }

    private func generateFirstFrame() {
        // TODO: Use Draw Things or Gemini to generate first frame
    }

    private func generateLastFrame() {
        // TODO: Use Draw Things or Gemini to generate last frame
    }

    private func autoGenerateDirection() {
        // TODO: Use MiniMaxPromptService to generate motion direction
    }

    private func sendToVidu() {
        // TODO: Use ViduAPIService to send first+last frame
    }

    private func queueForBatch() {
        // TODO: Add to store.viduQueue
    }
}
