import SwiftUI

@available(macOS 26.0, *)
struct ShotProductionStripView: View {
    @Bindable var store: AnimateStore
    let scene: AnimationScene
    let shot: AnimationSceneShot
    let shotIndex: Int

    @State private var motionDirection = ""
    @State private var durationSeconds: Double = 4.0
    @State private var hasAppeared = false

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                // Header
                headerSection
                Divider()
                // Motion direction
                motionSection
                Divider()
                // Timing and Vidu controls
                viduSection
            }
            .padding()
        }
        .onAppear { loadFromShot() }
    }

    private var headerSection: some View {
        HStack(spacing: 12) {
            VStack(alignment: .leading, spacing: 2) {
                Text("Shot \(shotIndex + 1)")
                    .font(.headline)
                Text(scene.name)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            if let cameraShot = shot.cameraShot {
                Text(cameraShot.rawValue)
                    .font(.caption)
                    .padding(.horizontal, 8).padding(.vertical, 4)
                    .background(.quaternary.opacity(0.2), in: Capsule())
            }
            Text("Duration: \(String(format: "%.1fs", durationSeconds))")
                .font(.caption.monospacedDigit())
                .foregroundStyle(.secondary)
        }
    }


    private var motionSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Motion Direction")
                    .font(.subheadline.weight(.semibold))
                Spacer()
                Button {
                    autoGenerateDirection()
                } label: {
                    Label("Auto-Generate", systemImage: "sparkles")
                }
                .buttonStyle(.bordered).controlSize(.small)
                .disabled(store.miniMaxAPIKey.isEmpty)
            }

            ResizablePromptEditor(
                text: $motionDirection,
                persistenceID: "shotProduction.motionDirection",
                minHeight: 60,
                defaultHeight: 90
            )
                .font(.callout)
                .padding(6)
                .background(.quaternary.opacity(0.15), in: RoundedRectangle(cornerRadius: 8))
        }
    }

    private var viduSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("Vidu Q3").font(.subheadline.weight(.semibold))

            VStack(alignment: .leading, spacing: 4) {
                Text("Duration").font(.caption)
                Slider(value: $durationSeconds, in: 0.5...16, step: 0.5)
                    .frame(width: 200)
                Text("\(String(format: "%.1f", durationSeconds))s (max 16s)")
                    .font(.caption2).foregroundStyle(.secondary)
            }

            HStack(spacing: 8) {
                Button {
                    sendToVidu()
                } label: {
                    Label("Send to Vidu", systemImage: "play.fill")
                }
                .buttonStyle(.borderedProminent).controlSize(.small)
                .disabled(store.viduAPIKey.isEmpty)

                Button {
                    queueForBatch()
                } label: {
                    Label("Queue for Batch", systemImage: "tray.and.arrow.down")
                }
                .buttonStyle(.bordered).controlSize(.small)
            }
        }
    }

    // MARK: - Actions

    private func loadFromShot() {
        let fg = shot.shotFrameGeneration
        motionDirection = fg?.motionDirection ?? ""
        durationSeconds = fg?.durationSeconds ?? 4.0
        hasAppeared = true
    }


    private func autoGenerateDirection() {
        // TODO: Use MiniMaxPromptService to generate motion direction
    }

    private func sendToVidu() {
        // Hard-code aspect ratio to 4:3
        // First/last frames are read from the scene's Imagine gallery
        let gallery = store.imagineGallery(for: scene.id, shotIndex: shotIndex)
        let firstFramePath = gallery?.selectedBeginningPath
        let lastFramePath = gallery?.selectedEndPath
        let aspectRatio = "4:3"

        // TODO: Use ViduAPIService to send first+last frame paths and aspectRatio
    }

    private func queueForBatch() {
        // TODO: Add to store.viduQueue
    }
}
