import Foundation
import SceneKit

/// Scans a directory for FBX/DAE motion clip files and generates
/// `Animate3DMotionSetDescriptor` entries for the motion registry.
///
/// Usage: FBXMotionRegistryScanner.scan(directory:) → [Animate3DMotionSetDescriptor]
@available(macOS 26.0, *)
struct FBXMotionRegistryScanner: Sendable {

    struct ScanResult: Sendable {
        let descriptors: [Animate3DMotionSetDescriptor]
        let scannedFileCount: Int
        let errorCount: Int
        let errors: [String]
    }

    /// Scan a directory recursively for FBX/DAE files and produce motion descriptors.
    static func scan(
        directory: URL,
        relativeToProjectURL projectURL: URL
    ) async -> ScanResult {
        let fm = FileManager.default
        let enumerator = fm.enumerator(
            at: directory,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        )

        var descriptors: [Animate3DMotionSetDescriptor] = []
        var scannedCount = 0
        var errors: [String] = []

        while let url = enumerator?.nextObject() as? URL {
            let ext = url.pathExtension.lowercased()
            guard ["fbx", "dae", "bvh"].contains(ext) else { continue }

            scannedCount += 1
            let motionID = motionIDFromFilename(url.deletingPathExtension().lastPathComponent)
            let title = titleFromFilename(url.deletingPathExtension().lastPathComponent)
            let tags = tagsFromFilename(url.deletingPathExtension().lastPathComponent)

            // Try to get relative path
            let fullPath = url.path
            let projectPath = projectURL.path
            let relativePath: String
            if fullPath.hasPrefix(projectPath) {
                relativePath = String(fullPath.dropFirst(projectPath.count + 1))
            } else {
                relativePath = fullPath
            }

            // Probe the file for frame count (optional — graceful skip)
            var holdMultiplier: Int? = nil
            if let clip = try? FBXMotionClipLoader.load(from: url) {
                holdMultiplier = clip.frameCount > 8 ? 2 : 1
            }

            let descriptor = Animate3DMotionSetDescriptor(
                motionID: motionID,
                title: title,
                relativePath: relativePath,
                tags: tags,
                notes: "Auto-generated by FBXMotionRegistryScanner",
                preferredHoldMultiplier: holdMultiplier
            )
            descriptors.append(descriptor)
        }

        return ScanResult(
            descriptors: descriptors,
            scannedFileCount: scannedCount,
            errorCount: errors.count,
            errors: errors
        )
    }

    // MARK: - Filename Parsing

    private static func motionIDFromFilename(_ name: String) -> String {
        name.lowercased()
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "-", with: "_")
            .filter { $0.isLetter || $0.isNumber || $0 == "_" }
    }

    private static func titleFromFilename(_ name: String) -> String {
        // "walk_forward_01" → "Walk Forward 01"
        name.replacingOccurrences(of: "_", with: " ")
            .replacingOccurrences(of: "-", with: " ")
            .split(separator: " ")
            .map { $0.prefix(1).uppercased() + $0.dropFirst() }
            .joined(separator: " ")
    }

    private static func tagsFromFilename(_ name: String) -> [String] {
        let lower = name.lowercased()
        var tags: [String] = []
        let tagKeywords = ["walk", "run", "idle", "sit", "stand", "jump", "talk", "sing",
                           "gesture", "react", "turn", "look", "reach", "bow", "wave",
                           "fight", "dance", "pray", "cry", "laugh", "think", "wait"]
        for keyword in tagKeywords where lower.contains(keyword) {
            tags.append(keyword)
        }
        return tags
    }
}
